services: 
  notificaciones:
    build: .
    container_name: node-notify
    ports:
      - "8888"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge