services: 
  notificaciones:
    build: .
    container_name: node_notify
    ports:
      -"8888"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge